version: "3.8"

services:
    jekyll:
        image: jekyll/jekyll:4.2.0
        command: jekyll serve --drafts --watch --force_polling --incremental
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
